# Generated by Django 5.2.4 on 2025-10-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('care_instructions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_species/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant Species',
                'verbose_name_plural': 'Plant Species',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='PlantIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_identifications/%Y/%m/%d/')),
                ('predicted_name', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_identifications', to=settings.AUTH_USER_MODEL)),
                ('identified_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.plantspecies')),
            ],
            options={
                'verbose_name': 'Plant Identification',
                'verbose_name_plural': 'Plant Identifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlantCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('plant_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plantspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('user', 'plant_species')},
            },
        ),
    ]
