# Generated by Django 5.2.7 on 2025-10-12 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('reason', models.CharField(choices=[('low_confidence', 'Low confidence score'), ('multiple_matches', 'Multiple matches'), ('user_report', 'User reported issue'), ('unknown', 'Unknown species')], max_length=50)),
                ('confidence', models.FloatField()),
                ('submitted_by', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
